---

- name: create proxy env file
  template:
    src: proxy.j2
    dest: /etc/profile.d/proxy.sh
    owner: root
    group: root
    mode: 0744
  when: HTTP_PROXY is defined
  become: yes
  become_method: sudo
