---

- name: create proxy env file
  template:
    src: proxy.j2
    dest: /etc/profile.d/proxy.sh
    owner: root
    group: root
    mode: 0744
  when: HTTP_PROXY is defined
  become: yes
  become_method: sudo

- name: create proxy apt
  template:
    src: 90proxy.j2
    dest: /etc/apt/apt.conf.d/90proxy
    owner: root
    group: root
    mode: 0744
  when: HTTP_PROXY is defined and ansible_os_family == 'Debian'
  become: yes
  become_method: sudo
